# Shivam Agrawal   Roll No.:1805428

In [30]:
import numpy as np
from numpy import linalg

In [16]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]

In [18]:
print("Original Matrix:")
print("Matrix1:")
print(p)
print("Matrix2:")
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

Original Matrix:
Matrix1:
[[1, 0], [0, 1]]
Matrix2:
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


In [19]:
print("Original Matrix:")
print("Matrix1:")
print(p)
print("Matrix2:")
print(q)
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)

Original Matrix:
Matrix1:
[[1, 0], [0, 1]]
Matrix2:
[[1, 2], [3, 4]]
Outer product of the said two vectors:
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [20]:
print("Original Matrix:")
print("Matrix1:")
print(p)
print("Matrix2:")
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("Cross Product of the said two vectors(p, q):")
print(result1)
print("Cross Product of the said two vectors(q, p):")
print(result2)

Original Matrix:
Matrix1:
[[1, 0], [0, 1]]
Matrix2:
[[1, 2], [3, 4]]
Cross Product of the said two vectors(p, q):
[ 2 -3]
Cross Product of the said two vectors(q, p):
[-2  3]


In [22]:
a = np.array([[1, 0], [1, 2]])
print("Original 2-d Array:")
print(a)
print("Determinant of the Array:")
print(np.linalg.det(a))

Original 2-d Array:
[[1 0]
 [1 2]]
Determinant of the Array:
2.0


In [23]:
a = np.array([1,2,5])
b = np.array([2,1,0])
print("Original 1-d Arrays:")
print(a)
print(b) 
result = np.inner(a, b)
print("Inner product of the said vectors:",result)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print("Matrix1:")
print(x)
print("Matrix2:")
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)

Original 1-d Arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors: 4
Higher dimension arrays:
Matrix1:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix2:
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [24]:
m = np.mat("3 -2;1 0")
print("Original matrix:")
print(m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix:")
print(v)

Original matrix:
[[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [25]:
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


In [26]:
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the Matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of the Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [28]:
m = np.arange(9).reshape(3,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Sum of Diagonal Elements:",result)

Original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum of Diagonal Elements: 12


In [29]:
a = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(a)
print("Frobenius Norm:",np.linalg.norm(a, 'fro'))
print("Condition Number:",np.linalg.cond(a, 'fro'))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Frobenius Norm: 16.881943016134134
Condition Number: inf
